#!/usr/bin/env python3
"""
BERTiLM peptide baseline (single train/test split) with figure CSV export.

Workflow for one dataset:
1) Read dataset CSV with Set/Hit/Epitope/Sequence.
2) Read encoded text lines from BERTiLM step-one output.
3) Extract sequence embeddings using a pretrained Roberta model.
4) Train XGBoost on Set!=Test, predict on Set==Test.
5) Save per-sample predictions + metrics.
"""

from __future__ import annotations

import argparse
import os
from typing import Dict, List

import numpy as np
import pandas as pd
import torch
from scipy import stats
from sklearn import metrics
from tokenizers import Tokenizer
from tqdm import tqdm
from transformers import PreTrainedTokenizerFast, RobertaModel
from xgboost import XGBClassifier


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser("BERT peptide baseline save")
    parser.add_argument("--data_set", required=True, help="Input dataset CSV path.")
    parser.add_argument("--encoded_txt", required=True, help="Encoded TXT path generated by build_vocabulary_files.py.")
    parser.add_argument("--tokenizer_file", required=True, help="Tokenizer .json path.")
    parser.add_argument("--model_dir", required=True, help="Path to pretrained Roberta model dir.")
    parser.add_argument("--max_length", type=int, default=512, help="Tokenizer truncation max_length.")

    parser.add_argument("--batch_size", type=int, default=64, help="Embedding extraction batch size.")
    parser.add_argument("--n_estimators", type=int, default=1200)
    parser.add_argument("--learning_rate", type=float, default=0.03)
    parser.add_argument("--max_depth", type=int, default=4)
    parser.add_argument("--n_jobs", type=int, default=8)
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument("--out_csv", required=True, help="Output prediction CSV.")
    parser.add_argument("--metric_txt", required=True, help="Output metrics TXT.")
    return parser.parse_args()


def _safe_roc_auc(y_true: np.ndarray, y_prob: np.ndarray) -> float:
    if len(np.unique(y_true)) < 2:
        return float("nan")
    return float(metrics.roc_auc_score(y_true, y_prob))


def _compute_metrics(y_true: np.ndarray, y_pred: np.ndarray, y_prob: np.ndarray) -> Dict[str, float]:
    acc = float(metrics.accuracy_score(y_true, y_pred))
    precision = float(metrics.precision_score(y_true, y_pred, zero_division=0))
    recall = float(metrics.recall_score(y_true, y_pred, zero_division=0))
    f1 = float(metrics.f1_score(y_true, y_pred, zero_division=0))
    bal_acc = float(metrics.balanced_accuracy_score(y_true, y_pred))
    roc = _safe_roc_auc(y_true, y_prob)
    ap = float(metrics.average_precision_score(y_true, y_prob))
    youden_j = float("nan")
    if len(np.unique(y_true)) >= 2:
        fpr, tpr, _ = metrics.roc_curve(y_true, y_prob)
        youden_j = float(np.max(tpr - fpr))
    t_stat = float("nan")
    p_val = float("nan")
    try:
        t_stat, p_val = stats.ttest_rel(y_true, y_pred)
        t_stat = float(t_stat)
        p_val = float(p_val)
    except Exception:
        pass
    return {
        "ACC": acc,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "Balanced_Accuracy": bal_acc,
        "ROC_AUC": roc,
        "PR_AUC(AP)": ap,
        "Youdens_J": youden_j,
        "t_test_t": t_stat,
        "p_value": p_val,
    }


def _save_metrics(path: str, metric_map: Dict[str, float]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    ordered = [
        "ACC",
        "Precision",
        "Recall",
        "F1",
        "Balanced_Accuracy",
        "ROC_AUC",
        "PR_AUC(AP)",
        "Youdens_J",
        "t_test_t",
        "p_value",
    ]
    with open(path, "w", encoding="utf-8") as f:
        for key in ordered:
            f.write(f"{key}: {metric_map.get(key, float('nan')):.6f}\n")


def load_encoded_lines(path: str) -> List[str]:
    with open(path, "r", encoding="utf-8") as f:
        lines = [ln.strip() for ln in f if ln.strip()]
    return lines


def load_tokenizer(tokenizer_file: str) -> PreTrainedTokenizerFast:
    # Validate tokenizer file first (useful error early).
    _ = Tokenizer.from_file(tokenizer_file)
    tok = PreTrainedTokenizerFast(
        tokenizer_file=tokenizer_file,
        padding_side="right",
        truncation_side="right",
        pad_token="<pad>",
        bos_token="<s>",
        eos_token="</s>",
        unk_token="<unk>",
        cls_token="<s>",
        sep_token="</s>",
        mask_token="<mask>",
        additional_special_tokens=["<|endoftext|>"],
    )
    return tok


def embed_texts(
    texts: List[str],
    tokenizer: PreTrainedTokenizerFast,
    model: RobertaModel,
    device: torch.device,
    max_length: int,
    batch_size: int,
) -> np.ndarray:
    vecs: List[np.ndarray] = []
    model.eval()
    with torch.no_grad():
        for i in tqdm(range(0, len(texts), batch_size), desc="Embedding", leave=False):
            batch = texts[i : i + batch_size]
            enc = tokenizer(
                batch,
                padding="max_length",
                truncation=True,
                max_length=max_length,
                add_special_tokens=False,
                return_tensors="pt",
            )
            input_ids = enc["input_ids"].to(device)
            attention_mask = enc["attention_mask"].to(device)
            out = model(input_ids=input_ids, attention_mask=attention_mask)
            hidden = out.last_hidden_state  # [B, L, H]
            mask = attention_mask.unsqueeze(-1).float()  # [B, L, 1]
            denom = torch.clamp(mask.sum(dim=1), min=1.0)
            pooled = (hidden * mask).sum(dim=1) / denom  # [B, H]
            vecs.append(pooled.detach().cpu().numpy())
    return np.vstack(vecs).astype(np.float32)


def main() -> None:
    args = parse_args()
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    df = pd.read_csv(args.data_set)
    required_cols = ["Epitope", "Sequence", "Hit", "Set"]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise KeyError(f"Dataset missing required columns: {missing}")
    df = df.dropna(subset=["Epitope", "Sequence", "Set"]).copy()
    df["Epitope"] = df["Epitope"].astype(str).str.strip()
    df["Sequence"] = df["Sequence"].astype(str).str.strip()
    df = df[(df["Epitope"] != "") & (df["Sequence"] != "")].copy().reset_index(drop=True)
    df["Set_norm"] = df["Set"].astype(str).str.strip().str.lower()

    lines = load_encoded_lines(args.encoded_txt)
    if len(lines) != len(df):
        raise ValueError(
            f"Encoded line count mismatch: encoded={len(lines)} vs rows={len(df)} "
            f"for {args.data_set}. Ensure build_vocabulary_files used the same CSV."
        )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    tokenizer = load_tokenizer(args.tokenizer_file)
    model = RobertaModel.from_pretrained(args.model_dir, output_hidden_states=False).to(device)

    X = embed_texts(lines, tokenizer, model, device, args.max_length, args.batch_size)
    df["Hit_num"] = pd.to_numeric(df["Hit"], errors="coerce")

    test_mask = df["Set_norm"] == "test"
    if test_mask.sum() == 0 or (~test_mask).sum() == 0:
        raise ValueError("Set split invalid: need both Set==Test and Set!=Test rows.")

    train_df = df.loc[~test_mask].copy()
    test_df = df.loc[test_mask].copy()

    # Train labels must be available and binary.
    train_df = train_df[train_df["Hit_num"].notna()].copy()
    y_train = train_df["Hit_num"].astype(int).to_numpy()
    if len(np.unique(y_train)) < 2:
        raise ValueError("Training labels contain only one class; cannot train classifier.")

    X_train = X[train_df.index.to_numpy()]
    X_test = X[test_df.index.to_numpy()]

    pos = float((y_train == 1).sum())
    neg = float((y_train == 0).sum())
    scale_pos_weight = float(max(1.0, 1.3 * (neg / max(pos, 1.0))))

    clf = XGBClassifier(
        n_estimators=args.n_estimators,
        learning_rate=args.learning_rate,
        max_depth=args.max_depth,
        min_child_weight=8,
        subsample=0.85,
        colsample_bytree=0.85,
        gamma=0.5,
        reg_lambda=8.0,
        reg_alpha=0.0,
        max_delta_step=1,
        scale_pos_weight=scale_pos_weight,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=args.seed,
        n_jobs=args.n_jobs,
        tree_method="hist",
    )
    clf.fit(X_train, y_train)
    proba = clf.predict_proba(X_test)[:, 1]
    pred = (proba >= 0.5).astype(int)

    # Evaluate on labeled test rows only.
    y_test_num = pd.to_numeric(test_df["Hit_num"], errors="coerce")
    labeled_mask = y_test_num.notna().to_numpy()
    if not labeled_mask.any():
        metric_map = {k: float("nan") for k in _compute_metrics(np.array([0, 1]), np.array([0, 1]), np.array([0.5, 0.5])).keys()}
    else:
        y_eval = y_test_num[labeled_mask].astype(int).to_numpy()
        metric_map = _compute_metrics(y_eval, pred[labeled_mask], proba[labeled_mask])
    _save_metrics(args.metric_txt, metric_map)

    out_df = pd.DataFrame(
        {
            "Epitope": test_df["Epitope"].tolist(),
            "MHC": test_df["MHC"].tolist() if "MHC" in test_df.columns else [""] * len(test_df),
            "Sequence": test_df["Sequence"].tolist(),
            "True Y": y_test_num.tolist(),
            "Predicted Y": pred.astype(int).tolist(),
            "Predicted Probabilities Y": proba.astype(float).tolist(),
        }
    )
    out_df = out_df.sort_values(by="Predicted Probabilities Y", ascending=False).reset_index(drop=True)
    os.makedirs(os.path.dirname(args.out_csv), exist_ok=True)
    out_df.to_csv(args.out_csv, index=False)

    print(f"Prediction CSV saved: {args.out_csv}")
    print(f"Metrics TXT saved: {args.metric_txt}")
    for k, v in metric_map.items():
        print(f"{k}: {v:.6f}")


if __name__ == "__main__":
    main()
